### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by takuzoo0** [takuzoo0/furima-35226#10]
# URL
https://furima-35226.herokuapp.com/
# Basic認証のIDとパスワード
ID：TechCampUser
パスワード：oosaka97
# 出品者用のメールアドレスとパスワード
Email：test@test.com
パスワード：test123
# 購入者用のメールアドレスとパスワード
Email：test2@test.com
パスワード：test123

**Comment by takumi0530** [comment]
@takuzoo0 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/117910319-aee7a080-b316-11eb-8fd3-20959d760d00.png)


### **【補足】※達成要件には関係ありません**

所々フォームの形式にバラツキがあったり、エラーメッセージの表示が乱れている部分がありましたので、見本アプリのように揃えるとより良いものになると思います！

**◾︎フォーム形式のバラツキ**

- 出品ページ
- 編集ページ
- 購入ページ

**◾︎エラーメッセージの乱れ**

- 購入ページ

<img width="651" alt="スクリーンショット 2021-05-12 11 40 43" src="https://user-images.githubusercontent.com/76197191/117910443-e6eee380-b316-11eb-97f5-2c9726845c72.png">
